### ISSUE TITLE
I cant install it

### ISSUE THREAD

**Issue by pomponchik** [michaelneuper/hugo-texify3#6]
**Describe the bug**
When i run the `hugo server` command after installing the theme, i see an error:

```
Watching for changes in /Users/evgeniy.blinov/Desktop/Projects/my_site/site/{archetypes,assets,content,data,i18n,layouts,static,themes}
Watching for config changes in /Users/evgeniy.blinov/Desktop/Projects/my_site/site/hugo.toml, /Users/evgeniy.blinov/Desktop/Projects/my_site/site/themes/hugo-texify3/config.toml, /Users/evgeniy.blinov/Desktop/Projects/my_site/site/themes/hugo-texify3/config/_default
Start building sites …
hugo v0.123.8-5fed9c591b694f314e5939548e11cc3dcb79a79c+extended darwin/arm64 BuildDate=2024-03-07T13:14:42Z VendorInfo=brew

ERROR TOCSS-DART: failed to transform "/sass/layouts/content.scss" (text/x-scss). You need dart-sass-embedded in your system $PATH.: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
ERROR TOCSS-DART: failed to transform "/sass/layouts/common.scss" (text/x-scss). You need dart-sass-embedded in your system $PATH.: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
ERROR TOCSS-DART: failed to transform "/sass/layouts/list.scss" (text/x-scss). You need dart-sass-embedded in your system $PATH.: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Built in 53 ms
Error: error building site: TOCSS-DART: failed to transform "/sass/layouts/common.scss" (text/x-scss). You need dart-sass-embedded in your system $PATH.: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
```

I installed the required thing and saw a new message running `hugo server`:

```
Watching for changes in /Users/evgeniy.blinov/Desktop/Projects/my_site/site/{archetypes,assets,content,data,i18n,layouts,static,themes}
Watching for config changes in /Users/evgeniy.blinov/Desktop/Projects/my_site/site/hugo.toml, /Users/evgeniy.blinov/Desktop/Projects/my_site/site/themes/hugo-texify3/config.toml, /Users/evgeniy.blinov/Desktop/Projects/my_site/site/themes/hugo-texify3/config/_default
Start building sites …
hugo v0.123.8-5fed9c591b694f314e5939548e11cc3dcb79a79c+extended darwin/arm64 BuildDate=2024-03-07T13:14:42Z VendorInfo=brew

ERROR POSTCSS: failed to transform "css/common.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: binary with name "npx" not found
ERROR POSTCSS: failed to transform "css/content.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: binary with name "npx" not found
Built in 1963 ms
Error: error building site: POSTCSS: failed to transform "css/common.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: binary with name "npx" not found
```

I did `npm install postcss-cli` and a saw it running `hugo server`:

```
Watching for changes in /Users/evgeniy.blinov/Desktop/Projects/my_site/site/{archetypes,assets,content,data,i18n,layouts,package.json,static,themes}
Watching for config changes in /Users/evgeniy.blinov/Desktop/Projects/my_site/site/hugo.toml, /Users/evgeniy.blinov/Desktop/Projects/my_site/site/themes/hugo-texify3/config.toml, /Users/evgeniy.blinov/Desktop/Projects/my_site/site/themes/hugo-texify3/config/_default
Start building sites …
hugo v0.123.8-5fed9c591b694f314e5939548e11cc3dcb79a79c+extended darwin/arm64 BuildDate=2024-03-07T13:14:42Z VendorInfo=brew

ERROR POSTCSS: failed to transform "css/common.css" (text/css): Error: Cannot find module 'autoprefixer'
Require stack:
- /Users/evgeniy.blinov/Desktop/Projects/my_site/site/themes/hugo-texify3/postcss.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/evgeniy.blinov/Desktop/Projects/my_site/site/themes/hugo-texify3/postcss.config.js:2:13)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at cjsLoader (node:internal/modules/esm/translators:358:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/evgeniy.blinov/Desktop/Projects/my_site/site/themes/hugo-texify3/postcss.config.js'
  ]
}
ERROR POSTCSS: failed to transform "css/content.css" (text/css): Error: Cannot find module 'autoprefixer'
Require stack:
- /Users/evgeniy.blinov/Desktop/Projects/my_site/site/themes/hugo-texify3/postcss.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/evgeniy.blinov/Desktop/Projects/my_site/site/themes/hugo-texify3/postcss.config.js:2:13)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at cjsLoader (node:internal/modules/esm/translators:358:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/evgeniy.blinov/Desktop/Projects/my_site/site/themes/hugo-texify3/postcss.config.js'
  ]
}
Built in 1973 ms
Error: error building site: POSTCSS: failed to transform "css/common.css" (text/css): Error: Cannot find module 'autoprefixer'
Require stack:
- /Users/evgeniy.blinov/Desktop/Projects/my_site/site/themes/hugo-texify3/postcss.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/evgeniy.blinov/Desktop/Projects/my_site/site/themes/hugo-texify3/postcss.config.js:2:13)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at cjsLoader (node:internal/modules/esm/translators:358:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/evgeniy.blinov/Desktop/Projects/my_site/site/themes/hugo-texify3/postcss.config.js'
  ]
}
```

So, i can't install it.

**Comment by Ginner** [comment]
My experience was exactly the same. I followed the proposed solution in #8 and installed `autoprefixer` and `postcss-import` witch solved it for me (`npm install autoprefixer` and `npm install postcss-import`).

Hope it helps.
